package extractor

import "testing"

func TestUsableBodyRejectsHMSoftBlock(t *testing.T) {
	body := []byte(`<html><head><title>Access Denied</title></head><body>
You don't have permission to access this page. Reference #18.abc
</body></html>`)

	if usableBody("https://www2.hm.com/it_it/productpage.1341273001.html", body) {
		t.Fatal("H&M soft-block page must not stop the fallback chain")
	}
}

func TestUsableBodyAcceptsHMProductPage(t *testing.T) {
	body := []byte(`<div data-testid="size-selector"><ul data-testid="grid">
<li><div data-testid="sizeButton-0" aria-label="Taglia XS: esaurita."><div>XS</div></div></li>
</ul></div>`)

	if !usableBody("https://www2.hm.com/it_it/productpage.1341273001.html", body) {
		t.Fatal("real H&M product page must be accepted")
	}
}

func TestUsableBodyKeepsGenericBehaviour(t *testing.T) {
	if !usableBody("https://example.com/product", []byte("any response body")) {
		t.Fatal("generic sites must keep accepting non-challenge bodies")
	}
}

func TestIsBotChallengeDetectsWordfenceBlock(t *testing.T) {
	// Wordfence localises every visible string on this page, so detection keys off the
	// documentation link its WAF block templates hardcode instead. This body is the
	// Polish variant supermaluch.com actually served us.
	body := []byte(`<html><head><title>Twój dostęp do tej witryny został ograniczony przez właściciela witryny</title></head>
<body><div class="container"><h1>Twój dostęp do tej witryny został ograniczony przez właściciela witryny</h1>
<p class="documentation small">Kliknij tutaj, aby dowiedzieć się więcej:
<a href="https://www.wordfence.com/help/?query=locked-out" target="_blank" rel="noopener noreferrer">Dokumentacja</a></p>
</div></body></html>`)

	if !isBotChallenge(body) {
		t.Fatal("Wordfence block page must not reach the price parsers as a successful fetch")
	}
}

func TestIsBotChallengeDetectsEnglishWordfenceBlock(t *testing.T) {
	body := []byte(`<h1>Your access to this site has been limited by the site owner</h1>
<p class="generated small"><em>Generated by Wordfence at Tue, 12 Aug 2026 9:12:33 GMT.</em></p>`)

	if !isBotChallenge(body) {
		t.Fatal("English Wordfence block page must be detected")
	}
}

func TestIsBotChallengeAllowsOrdinaryPageMentioningWordfence(t *testing.T) {
	// A shop's own blog post about security plugins must not read as a block page.
	body := []byte(`<html><body><article><h1>How we secure the shop</h1>
<p>We use Wordfence and visit wordfence.com regularly.</p></article></body></html>`)

	if isBotChallenge(body) {
		t.Fatal("a page merely mentioning Wordfence must not be treated as a block")
	}
}
